version: "3.7"

services:
  web:
    build: .
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000:5000
    depends_on:
      - ui
    network_mode: "bridge"
    environment:
      - "API_URL=http://web:5000"
      - POSTGRES_USER=postgres
      - DB_HOST=host.docker.internal 
      - POSTGRES_DB=help_directory
      - POSTGRES_HOST_AUTH_METHOD=trust

  ui:
    image: covid-hackathon-ui:latest
    ports:
      - 80:80
    environment:
      - "API_URL=http://web:5000"
