
      - db
      - ui
  ui:
    image: covid-hackathon-ui:latest
    expose:
      - "80"
    environment:
      - "API_URL=http://web:5000"
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=help_directory
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: always
    networks:
      - default
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cache/:/etc/nginx/cache
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
volumes:
  postgres_data:
  certificates:
